tap "neovim/neovim"

brew "git"
brew "stow"
brew "node"
brew "zsh"
brew "powerlevel10k"
brew "tmux"
brew "neovim"

cask "brave-browser"
cask "visual-studio-code"
cask "alacritty"
cask "iterm2"
cask "font-jetbrains-mono-nerd-font"

